### ISSUE TITLE
Cgate web MQTT

### ISSUE THREAD

**Issue by pete173** [the1laz/cgateweb#11]
Hi
cgate 2.11.1 ,cgateweb,MQTT and openhab2 all this are running on Rpi
I am not able to send cbus commands to cgate form openhab.
I have checked MQTT logs from MQTT.fx client. Openhab2 and MQTT are working fine.But cbus lights does not operate.

**Comment by the1laz** [comment]
Hi, are you seeing any mqtt messages when you turn your lights on/off from your wall switches? Have you checked the logs for cgateweb and cgate?

**Comment by pete173** [comment]
No I didnt check the logs.
How to check the logs of cgateweb?
Is it possible to check without CNI or cbus installed?
I just want to confirm wether mqtt  , cgateweb and cgate are communicating.I dont have cbus setup right now.

**Comment by pete173** [comment]
hi
checkout this cgateweb status
![cgateweb status](https://user-images.githubusercontent.com/37950989/39409494-b614d376-4c05-11e8-83f4-bac44501d756.png)


messages of topics are displayed on cgateweb status as seen in image.

**Comment by pete173** [comment]
hi 
I have checked the cgate stauts also please check the attachment
![cgate status](https://user-images.githubusercontent.com/37950989/39417268-b33b04f2-4c70-11e8-86dc-f93e7677e12b.png)

**Comment by pete173** [comment]
I also checked from cbus keypad.It doesnt show on logs.

**Comment by pete173** [comment]
Any ideas on what is happening?..

**Comment by pete173** [comment]
Messages can be seen from mqtt client and cgateweb logs.Messages is not being sent from cgateweb to cgate.Event port and command port gets disconnected in cgateweb status.There is error in connecting cgate.

**Comment by pete173** [comment]
need your help.

**Comment by pete173** [comment]
[Unit]
Description=cgateweb
Wants=cgate.service
After=network.target cgate.service

[Service]
ExecStart=/usr/bin/node /usr/local/bin/cgateweb/index.js
RestartSec=10
Restart=always
User=root
Group=root
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/usr/local/bin/cgateweb

[Install]
WantedBy=multi-user.target


made some changes in cgateweb.service.This solved my issue
