### ISSUE TITLE
CBUS blinds..

### ISSUE THREAD

**Issue by lockyt** [the1laz/cgateweb#19]
Hey the1laz.  Good work with cgateweb - just what I needed to integrate CBUS with Home Assistant and works great!

Quick question.  With home assistant you can use an MQTT Cover (Blind). https://www.home-assistant.io/components/cover.mqtt/

However as you will see on the first paragraph of the link, the cover component is looking for state_open and state_closed not on/off.  I am fairly new to MQTT / CBUS - do you have any advice on how to make cgateweb work with covers in HA?  I can get it working as an MQTT light no worries, including using the 'light's' brightness to set height of the blind, however I want to use the MQTT cover so that its displayed as a blind, not a light..

Is cgateweb able to process state_open and state_closed?  If not, would it be hard to change to handle these events?  Happy to have a go but may need some advice.

I might be able to setup a template cover instead which may allow me to display the light as a blind.  But it is a bit of a hack and would prefer to do it properly if I can.

Thanks.

Lachlan.

**Comment by lockyt** [comment]
Also, there is a payload_stop command.  Obviously lights don't need a stop..  any ideas?

**Comment by lockyt** [comment]
Sorry - worked it out.  Worked fine straight out of the box.

**Comment by the1laz** [comment]
Sorry for the delay looking at this, good to hear it's all fine.
