### ISSUE TITLE
Autostart and autoreconnect

### ISSUE THREAD

**Issue by safepay** [the1laz/cgateweb#3]
This is a great bit of software and I got it working pretty quickly.
My only issue is that if I need to restart Cgate, then cgateweb fails to reconnect.
This also affects my booting, as cgateweb starts before CGate and therefore does not connect at boot.
I solved this in systemd by adding
RestartSec=10
to the [Service] section.
I also tried some dependency settings but these had no effect. Only the restartsec had an influence.

cgateweb.service
```
[Unit]
Description=cgateweb
Wants=cgate.service
After=network.target cgate.service

[Service]
ExecStart=/usr/bin/nodejs /usr/local/bin/cgateweb/index.js
RestartSec=10
Restart=always
User=root
Group=root
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/usr/local/bin/cgateweb

[Install]
WantedBy=multi-user.target
```
cgate.service
```
[Unit]
Description=cgate

[Service]
ExecStart=/usr/bin/java -Djava.awt.headless=true -jar -noverify /usr/local/bin/cgate/cgate.jar
Restart=always
User=root
Group=root
Environment=PATH=/usr/bin:/usr/local/bin
Environment=NODE_ENV=production
WorkingDirectory=/usr/local/bin/cgate

[Install]
WantedBy=multi-user.target

```
Does anyone else have these issues?

**Comment by the1laz** [comment]
Thanks, I'll update it. I might have this problem, but I wouldn't know because the pi is always running!

**Comment by the1laz** [comment]
Need to handle reconnect still...

**Comment by the1laz** [comment]
Fixed
