### ISSUE TITLE
Add request for current values on startup

### ISSUE THREAD

**Issue by nrepian** [the1laz/cgateweb#5]
I hope this is the correct place for a suggestion.

I thought it may be useful to have all cbus values broadcast once cgateweb has fully initialised. As it stands, any MQTT clients are only in sync once "cbus/write/#1/#2//getall" has been requested. Perhaps when the cgateweb service has started, it could broadcast these values? Optically, it could also request them every x minutes (perhaps defaulting to 24h) to compensate if there are any changes to the MQTT broker.

**Comment by the1laz** [comment]
Good idea, should be pretty easy to add, I'll have a go

**Comment by nrepian** [comment]
Thanks 👍

**Comment by PianSom** [comment]
Staggering coincidence - I was just about to suggest the same thing. 

At the moment I solve the issue (as a Home Assistant user) by having automated a  "getall" publication at startup and every hour. I was going to suggest (as an alternative to the above) that the MQTT retain flag is optionally added to all "read" publications. This introduces a potential issue if light status is changed while the MQTT broker is offline, I know. 

I am a bit nervous about the startup service suggestion - my mosquitto broker seems to be slow at getting started.

**Comment by the1laz** [comment]
No problem, I was planning on making both optional

**Comment by the1laz** [comment]
Also added a gettree option.

**Comment by the1laz** [comment]
@PianSom Would you like the optional retain bit too or does that work for you?

**Comment by PianSom** [comment]
Thanks for the work!

I'd appreciate an optional retain flag, if it's not too much more work

**Comment by the1laz** [comment]
Done already, so can't have been too much. :)

**Comment by the1laz** [comment]
@PianSom See the settings file, retainreads.

**Comment by PianSom** [comment]
Star! Thanks!
