### ISSUE TITLE
Integration with Home Assistant

### ISSUE THREAD

**Issue by nrepian** [the1laz/cgateweb#6]
I'm so pleased that this excellent C-Bus plugin exists, I've got it integrated with Home Assistant (HASS.io) and it works really well.

I previously operated the lights as simple ON/OFF switches, but as there is control available for brightness within cgateweb and the home assistant software, I thought I'd implement it. However, it appears that Home Assistant sends a /switch = ON/OFF command along with the brightness /ramp percentage - so it never ramps, it just looks at the switch command.

Are there any other users using cgateweb with Home Assistant, and if so, how did you get around this issue? It is a configuration question for Home Assistant, rather than a cgateweb configuration question, so I hope you don't mind me posting this here considering it relates directly to it.

Here is an example of my configuration.yaml:

  - platform: mqtt
    state_topic: "cbus/read/254/56/37/state"
    command_topic: "cbus/write/254/56/37/switch"
    brightness_command_topic: "cbus/read/254/56/37/level"
    brightness_command_topic: "cbus/write/254/56/37/ramp"
    payload_on: "ON"
    payload_off: "OFF"
    brightness_scale: "100"
    name: Office Main Light

**Comment by drmcinnes** [comment]
i made a small change in mine that seems to work despite my lack of JavaScript knowledge

https://github.com/drmcinnes/cgateweb/blob/master/index.js

it adds a variable to start the last group address and if an on command is received after a ramp it ignores it.

**Comment by PianSom** [comment]
The latest version of Home Assistant contains code which allows the addressing of this issue (see https://home-assistant.io/components/light.mqtt/ on_command_type)

**Comment by the1laz** [comment]
@nrepian are you happy with the home assistant fix that PianSom suggested?

**Comment by nrepian** [comment]
I've not had a change to try it yet, but it looks like it should fix this issue - thank you :).

**Comment by dougrathbone** [comment]
Chiming in to update this thread for future reference - there is a fork of cgateweb that works natively on home assistant (i'm the maintainer).

https://github.com/dougrathbone/cgateweb
https://github.com/dougrathbone/cgateweb-homeassistant
