### ISSUE TITLE
Upgraded at last

### ISSUE THREAD

**Issue by PianSom** [the1laz/cgateweb#8]
Hi

I finally got around to upgrading this weekend to the latest version. Thanks for all the work - the retained MQTT messages are working great.

A couple of issues:
- in the absence of upgrade instructions I copies across package.json and index.js (and updated my settings.js). I got a "could not find xml2js" error, figured that I needed something not installed, so globally installed xml2js - no joy. I then copied the installed xml2js to the node_modules folder inside cgateweb and it worked.  What could possibly go wrong??
- Perhaps not unrelated to the previous comment, I am not sure the the regular update is working. I have set getallperiod to 60 * 60, but I am not seeing updates come through. (This is evidenced by the following point, and by the fact that changing getallperiod to 60 does not generate an update once per minute.) Now I check, I am not sure getallonstart is working for me either - I certainly do not see mqtt messages when cgateweb restarts (other than "hello/world CBUS ON").
- I am seeing occasional events being dropped (which I did not notice in the previous version). I have cbus switches which operate two lighting circuits, but when operated only see the MQTT message relating to one of them. Only one event is reported in the cgatewb logs (with logging turned on), though two lighting circuits are operating e.g. Hit a switch twice gives : 
`Nov 06 08:07:58 hassbian node[11972]: C-Bus status received: 254/56/7 OFF
Nov 06 08:07:58 hassbian node[11972]: C-Bus status received: 254/56/7 0%
Nov 06 08:07:58 hassbian node[11972]: C-Bus status received: 254/56/17 OFF
Nov 06 08:07:58 hassbian node[11972]: C-Bus status received: 254/56/17 0%
Nov 06 08:08:00 hassbian node[11972]: C-Bus status received: 254/56/7 ON
Nov 06 08:08:00 hassbian node[11972]: C-Bus status received: 254/56/7 100%`
 (so the 17 ON is being lost) This is a sporadic error.

Any ideas on how to get further info?

**Comment by the1laz** [comment]
- Yeah, I really should sort the instructions out for this thing. Hopefully I'll get some more time for sorting this stuff in a few weeks. It probably just needed "npm install" to be run from the project directory (/usr/local/bin/cgateweb). I added xml2js as a dependency.
- Did you specify getallnetapp in the settings as well? Requesting the statuses requires specifying the particular net and app that you're after. Sorry, I didn't add instructions about it.
- Hmm, not sure about that. Might be something to do with the messages coming in quick succession? Could be a problem with my dodgy parsing. Maybe try uncommenting line 208 in index.js and see what gets logged? (if (logging == true) {console.log('Command data: ' + data);})

**Comment by PianSom** [comment]
Hi

Ah, no "getallnetapp" - that would explain it.  Now included; we shall see. Thanks.

I'll keep an eye on dropped messages and let you know if I can reproduce.

Cheers.

**Comment by the1laz** [comment]
Haven't heard back, closing for now.
